{% set name = "esda" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pysal/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 93e2736bb1071d875f464acb9f04ddac803bbedc5b6febfcadcedfd3edf91cd3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  skip: True  # [py<311]

requirements:
  host:
    - python
    - wheel
    - setuptools >=61.0
    # setuptools_scm[toml] >=6.2
    - setuptools_scm >=6.2
    - toml
    - pip
  run:
    - python
    - geopandas >=0.14
    - libpysal >=4.12
    - numpy >=1.26
    - pandas >=2.1
    - scikit-learn >=1.4
    - scipy >=1.12
    - shapely >=2.1
  run_constrained:
    - blas=*=openblas  # [osx and x86_64]
    - matplotlib-base >=3.8
    - numba >=0.58
    - rtree >=1.1
    - seaborn >=0.12

{% set test_path = "${SP_DIR}/esda/tests" %}  # [not win]
{% set test_path = "%SP_DIR%\\esda\\tests" %}  # [win]

{% set deselect_tests = "" %}
# Issue created: https://github.com/pysal/esda/issues/361
# E   FloatingPointError: invalid value encountered in voronoi_polygons
{% set deselect_tests = " not test_prominence_valid" %}
{% set deselect_tests = deselect_tests + " and not test_prominence_options" %}
{% set deselect_tests = deselect_tests + " and not test_isolation_options" %}
{% set deselect_tests = deselect_tests + " and not test_isolation_valid" %}
{% set deselect_tests = deselect_tests + " and not test_to_elevation" %}

test:
  source_files:
    - esda/tests/regions.zip
  imports:
    - esda
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # For some reason regions.zip is not copying to the test directory in the site-package.
    - cp   esda/tests/regions.zip ${SP_DIR}/esda/tests/  # [not win]
    - copy esda/tests/regions.zip %SP_DIR%/esda/tests/  # [win]
    # test_moran_local_mv uses 'geodatasets' package which is not available
    - pytest --ignore={{ test_path }}/test_moran_local_mv.py -k "not {{ deselect_tests }}" {{ test_path }}
  requires:
    - pip
    - pytest

about:
  home: https://pysal.org/esda
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Exploratory Spatial Data Analysis
  description: |
    ESDA is an open-source Python library for the exploratory analysis of spatial data. 
    A subpackage of PySAL (Python Spatial Analysis Library), it is under active development and includes methods for global and local spatial autocorrelation analysis.
  dev_url: https://github.com/pysal/esda
  doc_url: https://pysal.org/esda

extra:
  recipe-maintainers:
    - ocefpaf
