{% set version = "2.3.5" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: 93113eed65cfaa815f172bc6cc56b4712eef726fbab7de42494865104b9bcafd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.4
    - pip
  run:
    - python >3.4
    - libpysal
    - pandas
    - scikit-learn
    - scipy >=0.11

test:
  imports:
    - esda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Exploratory Spatial Data Analysis

extra:
  recipe-maintainers:
    - ocefpaf
