{% set version = "2.1.1" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: abecd2e33bf9b856e57b103de989e6b7a18391d9dcd8bc1a75f494af260405d4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >3.4
    - pip
  run:
    - python >3.4
    - libpysal
    - numpy
    - scipy >=0.11
    - scikit-learn

test:
  imports:
    - esda

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Package with statistics for exploratory spatial data analysis

extra:
  recipe-maintainers:
    - ocefpaf
