{% set version = "1.0.1.dev0" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: a3619f39703bf0541e290824a692d4dea5a6d4af02f98ae1e11b7dccc6075941

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - libpysal
    - numpy
    - python
    - scipy

test:
  imports:
    - esda
  requires:
    - nose

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Package with statistics for exploratory spatial data analysis

extra:
  recipe-maintainers:
    - ocefpaf
