{% set name = "esda" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pysal/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1e8ed7f0549274f435fb68bce8ef7539bdc74c63c0b2b110d6c907079ac55b4c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  skip: True  # [py<311]

requirements:
  host:
    - python
    - wheel
    - setuptools >=61.0
    # setuptools_scm[toml] >=6.2
    - setuptools_scm >=6.2
    - toml
    - pip
  run:
    - python
    - geopandas >=0.14
    - libpysal >=4.12
    - numpy >=1.26
    - pandas >=2.1
    - scikit-learn >=1.4
    - scipy >=1.12
    - shapely >=2.1
  run_constrained:
    - blas=*=openblas  # [osx and x86_64]
    - matplotlib>=3.8
    - numba >=0.58
    - rtree >=1.1
    - seaborn >=0.12

# Issue created: https://github.com/pysal/esda/issues/361
# E   FloatingPointError: invalid value encountered in voronoi_polygons
{% set deselect_tests = " --deselect=test_topo.py::TestTopo::test_prominence_valid" %}
{% set deselect_tests = deselect_tests + " --deselect=test_topo.py::TestTopo::test_prominence_options" %}
{% set deselect_tests = deselect_tests + " --deselect=test_topo.py::TestTopo::test_isolation_options" %}
{% set deselect_tests = deselect_tests + " --deselect=test_topo.py::TestTopo::test_isolation_valid" %}
{% set deselect_tests = deselect_tests + " --deselect=test_topo.py::TestTopo::test_to_elevation" %}


test:
  source_files:
    - esda/tests/regions.zip
  imports:
    - esda
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # For some reason regions.zip is not copying to the test directory in the site-package.
    - cp esda/tests/regions.zip ${SP_DIR}/esda/tests/  # [not win]
    - cp esda/tests/regions.zip %SP_DIR%/esda/tests/  # [win]
    - pytest --pyargs esda.tests {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://pysal.org/esda
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Exploratory Spatial Data Analysis
  description: |
    ESDA is an open-source Python library for the exploratory analysis of spatial data. 
    A subpackage of PySAL (Python Spatial Analysis Library), it is under active development and includes methods for global and local spatial autocorrelation analysis.
  dev_url: https://github.com/pysal/esda
  doc_url: https://pysal.org/esda

extra:
  recipe-maintainers:
    - ocefpaf
