travis:
  secure:
    BINSTAR_TOKEN: Ogb34d4QvQRSUOU9zg3LeHEGI4Dxlf0nf6E57OPbSKdgZPYqt6UyTtrjXJQZHCEJPB3Go0gNUxDefHgTNiha5dten872Xf/epCLyirfCuvI7QxBLdw37uIugIl7y3IUT5l7aAcLrwf+5QINN2Vs6VY6BzOaSLrQrK1mBzzsfMOsBwEGTKMTNKxeIvrmn+NzAGOVplmMU1wtA/IPMrbYZFxyj+nEcUWV2+1OYSGcZC7nGWnJzQrOXXLyfTOijuZ0m9gaDqNboaWF/chW6T1FyO4G5VXWbuXQp55vRgPgRLiuDVYfHrR5A5wKASmShq6r4LWcMd+QF//u5uav9zJXiuZYt7FdVClXQDr5HOqdgoDdV/FaLcu3TUEnRZB2FV0cDV72uLkMy1qkS1sSLKvP8MFn7zcN4tbGs0xtI0aa99fbGoVEuT8+K4KhZiMHriBpNETVRY4eNNAsZhdyIYLA+U6tKiEoQIQYoAdOFK9/5sFJB0tL5okV7KiBn27tbDoq8pdLVoq814Ke+u8UGXPXv/5DUUw1zxgc6i3J6hiqvd0VZMkb5XZFymcMen1zTohIuAtCtOWcbm/qLKjn7MlbfkyQb4lz20Yc76SJqEN6f43ImuRfoBEfl3f9T/adlPIRQQjLzaucs398w8tHdSbQzYwYedLfjKZpb8qbvtFG6yHA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
